apiVersion: v1
kind: Service
metadata:
  name: mautrix-whatsapp
  labels:
    app: mautrix-whatsapp
    app.kubernetes.io/name: mautrix-whatsapp
  namespace: matrix
spec:
  ports:
  - name: mautrix-whatsapp
    port: 29318 
  selector:
    app: mautrix-whatsapp

