apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: mautrix-signal
  name: mautrix-signal
  namespace: matrix
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: mautrix-signal
  template:
    metadata:
      labels:
        app: mautrix-signal
    spec:
      containers:
        - image: dock.mau.dev/mautrix/signal:latest
          name: mautrix-signal
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          ports:
            - containerPort: 29328
              name: "mautrix-sign"
          volumeMounts:
            - name: mautrix-signal-configmap-volume
              mountPath: "/data/config.yaml"
              subPath: config.yaml
            - name: mautrix-signal-configmap-volume
              mountPath: "/data/registration.yaml"
              subPath: registration.yaml
            - name: signald-nfs-pvc
              mountPath: "/signald"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: mautrix-signal-configmap-volume
          configMap:
            name: mautrix-signal-configmap
        - name: signald-nfs-pvc
          persistentVolumeClaim:
            claimName: signald-nfs-pvc
