apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: mautrix-signal-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./configmap.enc.yaml
