apiVersion: v1
kind: Service
metadata:
  name: mautrix-signal
  labels:
    app: mautrix-signal
    app.kubernetes.io/name: mautrix-signal
  namespace: matrix
spec:
  ports:
  - name: mautrix-signal
    port: 29328
  selector:
    app: mautrix-signal

