apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app
  namespace: argocd
spec:
  project: default
  source:
    path: gitops/argocd/apps
    repoURL: "git@github.com:kareemlukitomo/homelab.git"
    targetRevision: HEAD
    directory:
      recurse: true # <--- Here
  destination:
    namespace: "*"
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
