apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-clusters
  labels:
    app.kubernetes.io/name: postgres-clusters
    app.kubernetes.io/part-of: cnpg
    app.kubernetes.io/managed-by: argocd
    name: postgres-clusters
  namespace: argocd
spec:
  destination:
    namespace: matrix
    server: "https://kubernetes.default.svc"
  source:
    repoURL: "git@github.com:kareemlukitomo/homelab.git"
    targetRevision: HEAD
    path: cnpg-system/postgres-clusters
  sources: []
  project: default
