apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mautrix-whatsapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "git@github.com:kareemlukitomo/homelab.git"
    path: "matrix/mautrix-whatsapp"
    targetRevision: HEAD
    kustomize:
      namespace: matrix
  destination:
    server: "https://kubernetes.default.svc"
    namespace: matrix
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
