apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: dendrite-cluster-scheduled-backup
  labels:
    app.kubernetes.io/component: database-backup
spec:
  schedule: "0 * * * * *" # At 0 minutes past the hour, every 12 hours, starting at 11:00 PM
  backupOwnerReference: none
  immediate: false
  cluster:
    name: "dendrite-cluster"
