---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: synapse-db-secret
  namespace: matrix
spec:
  encryptedData:
    password: AgA3Q7m4vv5iwILN2s5uNSYccGb3CjJJNREMUV95UYfgmdzMhO1WGkH3DYP93rKYFPiYvpopJHnJgd8J9XTBy2iv/h6V6Q9c1rssXxrL/QfMuqLcV30gZ8ixGWFK83UGYOtnW3b2brjVptjttA5/JbOOzV79oTEJIs21sm734wTDf6ghBOXCqDrz0LDSGqPpgOokPbK6lu+stS50J8zRKQU9H+eVBAbx9CBdk3b1b2agjaSGttUjwxiMjLLF6re36yG/KFUcz1R/YhBvJBupUr7fN8XboyLMYnuOk8T0S5O8K6jzJveVVLas6q+nz4YbDoucB5GG769oChX/yVCP4TOIfk0esNcuQUQ1Zfb7jGeSHcA1FLShgyE1tuqYJ3u+2v5bmltOisKKF4NljiLXSem3Lr5ZoBkOelekYMfI4GJrEJzHlizrJzemwiTHzzasb8VXFOxn041kHIZj8T696uj7JLPnprEh8sAspSyDZEdjEjIUokpszpPSzl/dD7TMVfXRYruVHGdRpTpm3jJFyjpK5qCnPviTiYu1ptIsG4dVkjvJgPz98Z/D52E9X076vzRwXo6hMjEhzjiT3zizP9U57eWEYC+AdV2Z+nnKHtjLhtJX2fY4uJP7/BTrUvHsua1h1dSihCRq/S7W8JGpXpoeFAY85ukl3cG8KwDmzylYReNQnvgZkcUuJr5azkEG8DxUpqk5oTnrbP6ePhyYedzmbeMqS7YIbtMGhWpRNoSy3A==
    username: AgBLRVuAwpoL/BmLJtUrO/Wz1yXb2LpqW1tI5qkSDSSsqeF9q4zMaYjPqFETAgRu1tsfVXoTL+JIARhVlOZcMfldBhwF2hZ6I2UZODKjgvpSpMEjTEb5vYFk3IG2VGvmzjzZBlERUIm39eXiOwHqnh32ZMxq3m6SLFoZPh8GqRMxmhBtSleSKk6VhstGPOsfJTM4dQRHbTDVK1K5iA+IM0QXJURL1EW61BJjzJbr7Dq+i4Z4sjLnZinQVgwiF/xQqxDSFulPX6JpuXnTCmDu9uDfQHKYi0qClUDpOaJnaODvMAHQjagkOVDzE6t2Bb3hPHNndrUj0SfOcWr0gEY03uwRvzRWTlkKfkK20EiULHpvB/p8RkQmWEIyFFMDi6dIKkap2RtGN5Upzm8EilcQoGlhRNjfVXUYHWtYrQCCkuDd405vr8N3KgaixYXDAADwJTFIGezN9D4CA97seEhThvV1/dKercVNw8hdcQW78uRTnDswNXfWkqlmx+GhGpl3v8mM4hmLWaqG+B8omMJOwg7aSDvu6yw2UmgBbtSpW2XKpOsG+NhkCUQv98X1O3eJ7hzihycWMoP4TMrtzwfN1BmxqOlfOBNHn2p4oZbGUCtZj9Kd6W/56jr3f2zDHq/TJ2nfK4IAnjv6dGMq/KXwsk4bTQjdjiajaoiIvNnXLtARW1u4ESRyD30cLEie/7T701mkVDujYHTsLGCAvG0=
  template:
    metadata:
      creationTimestamp: null
      name: synapse-db-secret
      namespace: matrix
    type: kubernetes.io/basic-auth
