apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: synapse-cluster
  namespace: matrix
spec:
  instances: 3
  storage:
    size: 8Gi
  bootstrap:
    initdb:
      database: synapse
      owner: synapse_user
      dataChecksums: true
      encoding: "UTF8"
      localeCollate: "C"
      localeCType: "C"
      secret:
        name: synapse-db-secret
  superuserSecret:
    name: synapse-db-secret
  backup:
    barmanObjectStore:
      destinationPath: "gs://shaquillekareem/backup/homelab"
      googleCredentials:
        applicationCredentials:
          name: backup-creds
          key: gcsCredentials
