apiVersion: v1
kind: Secret
metadata:
    name: mysecret
type: Opaque
data:
    username: ENC[AES256_GCM,data:QocT+HAxiVY=,iv:R+m6tiP3T8AdWm26shhDGddOPwphQ4amCTnFMG2BP38=,tag:bL1AhjUDH8TKHQ1pCBj1XA==,type:str]
    password: ENC[AES256_GCM,data:wfcC+KNHKr8/8mWkJPJzjA==,iv:FXoL1lKyg4xo1t7wynnshNhdYr77W23Zl6CxK0vBzHQ=,tag:dQOZ8fOY1muPmzupvgIWCg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-08-03T13:04:22Z"
    mac: ENC[AES256_GCM,data:q+KWSF+70K9t/KLbb4ihUEHWneAk1l1DT1mfX8qdOnk98CsCrMYTuVxbm6MAb7FR680qUYt3z3QvLyR7eIgnuXe3BcULwCZ6rLog1nWs9RejbRmMu/kC2Vpk3TlvrD+5FeWpXJmRIEA0V5oOmAJEcn529fkwvIKbHIULsR0K3KY=,iv:w/ftfy8VV33Yruc50eeWHwbwnJuvCTMzi4r3WIqCnXg=,tag:SSA3+G4W5/ByqOCzpm/ZqA==,type:str]
    pgp:
        - created_at: "2024-08-03T13:04:22Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DT6AMeEvvTXYSAQdAN1cPhZMHg16GL4H7sXFK7fxj1BKOrS7b0JjfmIFNl00w
            5DkP4L91ylgu6IkzOOk3k7L+2QofHO4wdHCYMB1sPZGSdnZzwFzDI7UYN04PO5F5
            0l4B14nY+TRO1sUHcwvz9N0DYYKrLTLkecVF38lSXcBYJ3o5ZTBHCLr2Yuhdx3hd
            kH9Ead2HKpXlE5/EkHrxcNQEBi1q9hoP2yM/qbcCK+NESfMw/G/WZyRigpMk5q6R
            =Yqwq
            -----END PGP MESSAGE-----
          fp: 57CA390B905856D199930D8E1AF3A11F4741A16A
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.0
