apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mautrix-telegram
  name: mautrix-telegram
  namespace: matrix
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: mautrix-telegram
  template:
    metadata:
      labels:
        app: mautrix-telegram
    spec:
      containers:
        - image: dock.mau.dev/mautrix/telegram:latest
          name: mautrix-telegram
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          ports:
            - containerPort: 29317
              name: "mautrix-tele"
          volumeMounts:
            - name: mautrix-telegram-configmap-volume
              mountPath: "/data/config.yaml"
              subPath: config.yaml
            - name: mautrix-telegram-configmap-volume
              mountPath: "/data/registration.yaml"
              subPath: registration.yaml
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: mautrix-telegram-configmap-volume
          configMap:
            name: mautrix-telegram-configmap
