apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: mautrix-telegram-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./configmap.enc.yaml
