apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin-ingress
  namespace: notification
spec:
  ingressClassName: nginx
  rules:
  - host: video.kareem.one
    http:
      paths:
      - backend:
          service:
            name: jellyfin
            port:
              number: 8080
        path: /
        pathType: Prefix
