apiVersion: v1
kind: Service
metadata:
    name: jellyfin
    namespace: external
spec:
    type: ExternalName
    externalName: ENC[AES256_GCM,data:g9rGvpHYQ2WVOQ==,iv:L0PqMZaLG8tQZWWF/A6kqFWopzDNt8S7HNmj3QFEUWY=,tag:etVEH0Vv+CbtG0Rhz7uVoA==,type:str]
    ports:
        - port: ENC[AES256_GCM,data:W6F3Mw==,iv:d7+cvuLIqvJANaj3WjmlKft7a+l57BS54CGGJdQvQwo=,tag:jxiAdw8BQiwMtkAj6901VA==,type:int]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-08-08T20:39:49Z"
    mac: ENC[AES256_GCM,data:b6q7SrbN/t3i67u6KZNJQRNDAawMuAevxant6ERPADxsyJaWANUdk9eWQPDJna5q6q4LhikNpoRD6IfFT02AoF2gf9/YcU7GzqUyccgSaulQ8So3CFFfIDvuZwdqJ96uF9knukbGOnJO9XmaX3DILKLlIUPWlp8cOxdCUxjRv2E=,iv:Eiu7MTyMlylnIFp6fE0Lxu/FFLMk+iOz2q413+dMWDg=,tag:oijhHe/BtFaYByz3RUVFhQ==,type:str]
    pgp:
        - created_at: "2024-08-08T20:39:49Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA2wploviDREZAQ//UBqOJ1Dyp5atl480RU1sjqTs7r2Z/Lf6e8oW4CfMuXfL
            Ll38//GQDpFojjUSGht94ZaR6HBKyORq3W5H2olWvbPReMLPCPzz8cVkbgDtsaJ7
            +LH4z0Bg+q+0VGd9JhDwOp4xXvseAvBb3J9XTomCPZmIvDOhK/lMt1PcPmP22nMI
            +INHyIMXIG1jMfrF9NaCv0ag+66eB6PEDJlguwis4c+St/DkEKYlG61V0RFQ7xrM
            ItIG6qG3I5TVmXSfkgCoSZjhjAW540sk7qm/2KGwNJPO9HLNN04HOfv47TQ6U3xa
            8iZB40O4KxsDi2maRIpnVJ0rvPiNhFjXjj6TOP3tPtyRbGeAX2JzPU1sO4D/Hhwl
            t2lq9V47a18wBAiJ7QNEgqfJTYrn83yKU4haAggeWJJrJr0PuOLuE4udJ1f3oV93
            SF8/UNctcQN6Ox89ePiV/IuN3te2eB54HP7VXYl2D8jeoRb2l/ZR1YDy644Uhb9J
            LnwqGhfsG6WPdNeEx0GI1U6wlW8mVto9MPEEMW3+ocq71rHreGN74Fm9T/8q1+Dl
            M5DgX4mBuHOrK0f0JmKH078OZ3cYhSKyvnM2BAPAbM8eSVXVpfatIsuxKzY/l2ZL
            1AnrlOEvYuWrtwykVbmbkiKfYtLnnrKmNaEL3EiXw8t/q6tJevJyHGEscR46fUDS
            XgE479AFLrYSnlqafTeU8OVB+ojXCiWxsGrFF2Qj3jfMXJt1hgneCs6FaApt1Rqm
            V5EzGnLggdJXczaWigt9gqajPyMzkodCjPrWa0hzr6rqQtHBltzZaMC9MyUmNbc=
            =Fut5
            -----END PGP MESSAGE-----
          fp: 2B3289FB52F647985547AAFA78594004D427BD9B
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.0
