apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-helm-encrypted
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:kareemlukitomo/homelab.git
    path: gitops/argocd/helm-encrypted
    targetRevision: main
    kustomize:
      namespace: argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: "*"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
